# Generated by Django 3.0.1 on 2020-01-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0002_auto_20200121_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-products'),
            preserve_default=False,
        ),
    ]
