# Generated by Django 3.0.1 on 2020-01-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description djf f dfkl f fsklf  fjkls  fk lsjf sf lfjkfj '),
            preserve_default=False,
        ),
    ]
